In [3]:
# university monitors the elcticity usage (in units) of 4 hostes over 7 days(mon-sun)
# array name : electricity
# shape: (4,7)
# rows: (hostels (h1, h2 , h3 , h4))
# columns: (days (mon, tue, wed, thu, fri, sat, sun))

# create numpy arr using np.random.randint , values bw 120 and 650.
import numpy as np
electricity = np.random.randint(120, 650, size=(4, 7))
print(electricity)

[[410 224 146 474 606 429 258]
 [586 564 139 382 638 451 354]
 [349 305 431 507 296 378 583]
 [547 429 523 555 266 507 608]]


In [4]:
# print shape , dimension , total no, of elements and data types
print("Shape:", electricity.shape)
print("Dimensions:", electricity.ndim)
print("Total number of elements:", electricity.size)
print("Data type:", electricity.dtype)

Shape: (4, 7)
Dimensions: 2
Total number of elements: 28
Data type: int32


In [ ]:
# hostel - wise metrices
# find the avg electricity used per hostel , max usage per hostel , and identify which hostel has highest average usage.
ele_avg = np.mean(electricity, axis=1)   # average per hostel
ele_max = np.max(electricity, axis=1)    # max usage per hostel

print("\nAvg electricity usage per hostel:", ele_avg)
print("Max usage per hostel:", ele_max)

highest_avg_hostel_index = np.argmax(ele_avg)
print("\nHostel with highest average usage is: H", highest_avg_hostel_index + 1)



Avg electricity usage per hostel: [363.85714286 444.85714286 407.         490.71428571]
Max usage per hostel: [606 638 583 608]

Hostel with highest average usage is: H 4


In [8]:
# if electricity usage on any day greater than 550 units , apply a 20% discount on them.
discounted_electricity = np.where(electricity > 550, electricity * 0.8, electricity)
print("\nElectricity usage after applying discount on values greater than 550:\n", discounted_electricity)


Electricity usage after applying discount on values greater than 550:
 [[410.  224.  146.  474.  484.8 429.  258. ]
 [468.8 451.2 139.  382.  510.4 451.  354. ]
 [349.  305.  431.  507.  296.  378.  466.4]
 [547.  429.  523.  444.  266.  507.  486.4]]


In [9]:
# reshape the electricity data into a single row represnting weekly usage (Shape 1x 28).
reshaped_ele = electricity.reshape(1,-1)
print("\nReshaped electricity data (1x28):\n", reshaped_ele)


Reshaped electricity data (1x28):
 [[410 224 146 474 606 429 258 586 564 139 382 638 451 354 349 305 431 507
  296 378 583 547 429 523 555 266 507 608]]
