In [1]:
import numpy as np
import pandas as pd

# student marks data for 5 students in 3 subjects.
# ques 1:  show each student marks in each subject.
# ques 2: show total marks of each student.
# ques 3: Show the highest marks scored by each student across all subjects.
# ques 4: show who has scored highest in subject 3.
# ques 5: show all the students who have scored more than 50 marks in total.
# ques 6(Bonus): Find the average marks of each subject (column-wise average).
# ques 7(Bonus): Sort the students based on their total marks in descending order.
# ques 8(Bonus): students whose average marks are greater than class average
# ques 9 (Bonus): Replace all marks below 40 with 0 using NumPy masking.
# ques 10 (Bonus): Extract marks of Student 2 to Student 4 for Subject 2 and Subject 3 only.
# Axis 0 rows → Students
# Axis 1 columns→ Subjects
arr = np.array([
    [10, 9, 20],   # Student 1
    [45, 60, 55],   # Student 2
    [88, 92, 95],   # Student 3
    [30, 40, 35],   # Student 4
    [40, 4, 2]    # Student 5
])
arr

array([[10,  9, 20],
       [45, 60, 55],
       [88, 92, 95],
       [30, 40, 35],
       [40,  4,  2]])

In [2]:
# ques 1:  show each student marks in each subject.
print("each student marks in each subjecs are : \n", arr)
# ques 2
print("toatal marks of each students: \n", np.sum(arr, axis=1))
# ques 3 Show the highest marks scored by each student across all subjects.
# print("Highest marks per subject:\n", np.max(arr, axis=0))
print("highest marks scored by each students are: \n subject 1:",np.max(arr[:,0]), "\nsubject 2: ", np.max(arr[:,1]), "\nsubject 3: ", np.max(arr[:,2]))
# ques 4:
print("who has scored highest in subject 3 with marks: \n", np.argmax(arr[:,2]), "with marks: ", np.max(arr[:,2]))
#  ques 5: 
print("students who scored more than 50 marks in total in all 3 subjects: \n", np.where(np.sum(arr, axis=1) > 50)[0])

each student marks in each subjecs are : 
 [[10  9 20]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [40  4  2]]
toatal marks of each students: 
 [ 39 160 275 105  46]
highest marks scored by each students are: 
 subject 1: 88 
subject 2:  92 
subject 3:  95
who has scored highest in subject 3 with marks: 
 2 with marks:  95
students who scored more than 50 marks in total in all 3 subjects: 
 [1 2 3]


In [3]:
# ques 6 (Bonus)
print("average marks of each subject:\n", np.mean(arr, axis=0))
# ques 7 (Bonus)
total_marks = np.sum(arr, axis=1)
sorted_index = np.argsort(total_marks)[::-1]   # reverse for descending

print("students sorted based on total marks (descending):\n", arr[sorted_index])
# ques 8 (Bonus)
student_avg = np.mean(arr, axis=1)
class_avg = np.mean(arr)

print("students whose average marks > class average:\n",
      np.where(student_avg > class_avg)[0])
# ques 9 (Bonus)
arr_masked = arr.copy()
arr_masked[arr_masked < 40] = 0

print("marks after replacing below 40 with 0:\n", arr_masked)
# ques 10 (Bonus)
print("marks of student 2 to 4 for subject 2 and 3:\n", arr[1:4, 1:3])


average marks of each subject:
 [42.6 41.  41.4]
students sorted based on total marks (descending):
 [[88 92 95]
 [45 60 55]
 [30 40 35]
 [40  4  2]
 [10  9 20]]
students whose average marks > class average:
 [1 2]
marks after replacing below 40 with 0:
 [[ 0  0  0]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [40  0  0]]
marks of student 2 to 4 for subject 2 and 3:
 [[60 55]
 [92 95]
 [40 35]]


In [9]:
# Class work - where >50 - 1 else 0
result = np.where(arr > 50, 1, 0)

print("\n Students matrix where students have marks greater than 50: \n", result)
# Grade allocation : apply grading system based on students average.
# avg >= 85 - A, >= 70 - b, >= 50 - c, else no grade.
students_avg  = np.mean(arr, axis=1)
result_grade = np.where(students_avg >= 85, 'A', np.where(students_avg >= 70, 'B', np.where(students_avg >= 50, 'C', 'F')))
print("\n Students grades based on average marks: \n", result_grade)
# create a backup of the original array, and modify original array to 0, and check if modified or changed or not
backup = np.copy(arr)
print("\n backup arr: \n", backup)
# Modify original array
arr[:] = 0
print("\nOriginal array after modification:\n", arr)





 Students matrix where students have marks greater than 50: 
 [[0 0 0]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]]

 Students grades based on average marks: 
 ['F' 'C' 'A' 'F' 'F']

 backup arr: 
 [[10  9 20]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [40  4  2]]

Original array after modification:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
